site_name: 'Luna'

site_url: http://zzz.bwh.harvard.edu/luna

site_description: Documentation for the Luna software

site_author: S. M. Purcell

theme:
    name: 'material'

    features:
        - navigation.tabs
        - navigation.top
    
    palette:
      primary: 'indigo'
      accent: 'indigo'
      
#    custom_dir: '/usr/local/lib/python3.7/site-packages/mkdocs_material-3.2.0.dist-info/'

    highlightjs: false

    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s

markdown_extensions:
  - admonition
  - pymdownx.superfences

#extra_javascript:
#  - 'javascripts/extra.js'

extra_css:
  - 'stylesheets/extra.css'
      
nav:
 - Home:
     - Overview: 'index.md'
     - Updates: 'updates.md'
     - Tutorial: 'tut/tut1.md'
     - lunaC: 'luna/args.md'
     - lunaR: 'ext/R/index.md'
     - Commands: 'ref/index.md'
     - NSRR: 'nsrr.md'
     - Vignettes: 'vignettes/index.md'
     - Downloads: 'download/index.md'
     - FAQ: 'faq.md'

 - Updates: 'updates.md'

 - Tutorial: 
     - 'Quick start': 'tut/tut1.md'
     - 'Take two': 'tut/tut2.md'
     - 'Deeper dive': 'tut/tut3.md'
     - '/R/epeat': 'tut/tut4.md'

 - lunaC:
    - 'Overview' : 'luna/args.md'
    - 'Output': 'luna/destrat.md'
    - 'dmerge': 'merge/merge.md'
    - 'dmerge example': 'merge/merge-example.md'


 - lunaR:
    - Overview: 'ext/R/index.md'
    - Example usage: 'ext/R/example.md'
    - Reference: 'ext/R/ref.md'
    - Plotting: 'ext/R/viz.md'
    
 - Commands:
    - 'Overview': 'ref/index.md'
    - 'Summaries': 'ref/summaries.md'
    - 'Annotations': 'ref/annotations.md'
    - 'Expressions': 'ref/evals.md'
    - 'Epochs': 'ref/epochs.md'
    - 'Masks': 'ref/masks.md'
    - 'Manipulations': 'ref/manipulations.md'
    - 'Outputs': 'ref/outputs.md'
    - 'Filters': 'ref/fir-filters.md'
    - 'Artifacts': 'ref/artifacts.md'
    - 'Hypnograms': 'ref/hypnograms.md'
    - 'SUDS': 'ref/suds.md'
    - 'Spectral analyses': 'ref/power-spectra.md'
    - 'Spindles/SO ': 'ref/spindles-so.md'
    - 'Coupling/connectivity': 'ref/cc.md'
    - 'Interval-based': 'ref/intervals.md'
    - 'PSC': 'ref/psc.md'
    - 'Spatial': 'ref/spatial.md'
    - 'ICA': 'ref/ica.md'    
    - 'EEG microstates': 'ref/ms.md'
    - 'Clustering': 'ref/clustering.md'
    - 'Association' : 'ref/assoc.md'
    - 'Experimental ': 'ref/exp.md'
 
 - NSRR:
    - 'Working with NSRR data' : 'nsrr.md'
    - 'NAP web portal' : 'nap.md' 

 - Vignettes: 
    - 'Index' : 'vignettes/index.md'
    - 'Artifacts' : 'vignettes/chep.md'
    - 'EDF+D & annotations' : 'vignettes/annots.md'
    - 'Cox & Fell' : 'vignettes/rcox.md'
    - 'Visualizing NSRR data' : 'vignettes/dataplots.md'
    - 'Compressed EDFs' : 'vignettes/edfz.md'
    - 'EEG polarity' : 'vignettes/nsrr-polarity.md'
    - 'UMAP clustering' : 'vignettes/nsrr-umap.md'

 - Downloads:
    - 'Overview': 'download/index.md'
    - 'Binaries': 'download/exec.md'
    - 'Source': 'download/source.md'
    - 'Docker': 'download/docker.md'
    - 'Data': 'download/data.md'
    - 'Notes': 'download/misc.md'

 - FAQ: 'faq.md'
